### ISSUE TITLE
能否开启详细页添加关注功能

### ISSUE THREAD

**Issue by yilezhu** [esofar/cnblogs-theme-silence#1]
博主能否考虑开启文章详细页的添加关注功能，如果推荐功再能够再右下角浮动就更好了。主题不错！
还有就是，自动生成的目录宽度，会随着目录文本的长度增加而变宽，会很难看，可以考虑给个最大宽度，超过自动换行！我不是很懂css只是建议哈！

**Comment by liuzhenyulive** [comment]
是的   我也觉得这个需求很有必要  阅读文章的时候找不到关注的按钮了 期待添加

**Comment by liuzhenyulive** [comment]
![image](https://user-images.githubusercontent.com/23184470/47954126-805c1280-dfc1-11e8-835e-3f7c21c065ae.png)
建议在这里添加关注按钮

**Comment by liuzhenyulive** [comment]
持续期待关注按钮中  😄 哈哈

**Comment by esofar** [comment]
@yilezhu 
@liuzhenyulive 
已经在 [v1.1.0](https://github.com/esofar/cnblogs-theme-silence/releases/tag/v1.1.0) 版本中添加关注按钮，请知晓，多谢支持！

**Comment by liuzhenyulive** [comment]
感谢  感谢

**Comment by BlueHtml** [comment]
“关注”按钮在右下角，毫无存在感。打算放弃时，偶然找到了。。。

**Comment by esofar** [comment]
@BlueHtml 感觉您的建议，下个版本会考虑调整样式。

**Comment by BlueHtml** [comment]
> @BlueHtml 感谢您的建议，下个版本会考虑调整样式。

关注按钮的样式和主题还是蛮搭的。只是如果没有预先提醒的话，很难注意到。不过一旦知道了就OK了。
该主题就是为了阅读的纯粹，关注按钮的位置倒是不太好安排了。
以上只是个人见解，博主适当参考下。总之我觉得主题挺好的。
