### ISSUE TITLE
3.0.0-beta2 样式问题

### ISSUE THREAD

**Issue by WeihanLi** [esofar/cnblogs-theme-silence#113]
1. 文章详情没有收藏按钮了，感觉最好加一下收藏按钮吧

> 我现在是加了一个样式来解决的，`#green_channel { display: block !important; }`

2. dark 模式，看不清楚文章中的文字

![image](https://user-images.githubusercontent.com/7604648/96202841-d948c980-0f92-11eb-9521-076647622b06.png)

3. mobile 上导航栏感觉有点问题，右上角有一块黑色的框

![image](https://user-images.githubusercontent.com/7604648/96202663-5c1d5480-0f92-11eb-87ca-4714caea520e.png)

博客地址：<https://www.cnblogs.com/weihanli/p/how-to-stack-overflow.html>

**Comment by esofar** [comment]
你难道不怀疑是自己没部署好吗，请认真阅读[文档](https://esofar.github.io/cnblogs-theme-silence/)，（我感觉部署过程写的非常清楚了）。

**Comment by WeihanLi** [comment]
额，之前看的时候部署指南里是空的（可能是缓存的原因吧），，我先看看文档，抱歉
