### ISSUE TITLE
宽屏和窄屏情况下，导航栏显示的条目不一致

### ISSUE THREAD

**Issue by hippieZhou** [esofar/cnblogs-theme-silence#13]
在宽屏情况下，不会显示 Tag 导航条目，但是在移动设备上，就会显示，如下图所示：

- 宽屏情况

![1](https://user-images.githubusercontent.com/13598361/56257108-c800d180-60fd-11e9-9f82-0ed120d33f6b.png)

- 移动设备

![2](https://user-images.githubusercontent.com/13598361/56257112-ca632b80-60fd-11e9-8a1f-b8453fc892b1.png)

不知道这种情况是我的后台设置问题还是一个  Issue

**Comment by esofar** [comment]
是这样的，屏宽`767px`以上主题是可以显示侧边栏的，自然可以显示「我的标签」，但是 `767px`以下主题会隐藏会左侧栏，就不能显示「我的标签」，所以我在导航栏加了一个「标签 」按钮，方便用户快速浏览博客所有的标签。

**Comment by hippieZhou** [comment]
嗯，明白了，谢谢。
