### ISSUE TITLE
打赏时闪烁

### ISSUE THREAD

**Issue by fenggwsx** [esofar/cnblogs-theme-silence#141]
本人博客样例：[https://www.cnblogs.com/fenggwsx/p/14252994.html](https://www.cnblogs.com/fenggwsx/p/14252994.html)
在鼠标移到打赏按钮时会发生图片闪烁
猜测原因是图片出来后覆盖了按钮使鼠标不在按钮上而引起图片隐藏，然而图片已隐藏鼠标就在按钮上又触发图片显示的循环

**Comment by StarkLiu9973** [comment]
同样的问题

**Comment by 15b883** [comment]
![image](https://user-images.githubusercontent.com/18657703/106127612-a91be400-6199-11eb-8d74-15cf98224207.png)
你把你的 paypal 这里设置成null。。。我之前遇到过跟你一样的问题。就是这里设置的问题。

**Comment by Mrxqb** [comment]
我刚才去了一下esofar博主的博客里面，发现博主的打赏功能是正常的，于是找到了问题的原因，确实如“fenggwsx”提问所说的问题一样，但是并不是paypal设置的问题，问题在于配置选项中“sponsor”text设置赞赏友好提示。如果此处没有任何填写设置的话，并不会自动填充'Buy me a cup of coffee ☕.'为默认值，所以此处空出来的空间导致赞赏按钮上移出现了不断闪烁的问题，所以建议暂时最好配置一段text赞赏时的友好提示就好了。

**Comment by fenggwsx** [comment]
> 我刚才去了一下esofar博主的博客里面，发现博主的打赏功能是正常的，于是找到了问题的原因，确实如“fenggwsx”提问所说的问题一样，但是并不是paypal设置的问题，问题在于配置选项中“sponsor”text设置赞赏友好提示。如果此处没有任何填写设置的话，并不会自动填充'Buy me a cup of coffee ☕.'为默认值，所以此处空出来的空间导致赞赏按钮上移出现了不断闪烁的问题，所以建议暂时最好配置一段text赞赏时的友好提示就好了。

谢谢，我刚刚按照你说的加了text现在可以了
