### ISSUE TITLE
navbar的样式受字体族影响产生高度不一致

### ISSUE THREAD

**Issue by bladeXue** [esofar/cnblogs-theme-silence#146]
版本号@3.0.0-beta3，Navbar的项的居中样式是盒子做的，在我Windows的Chrome中，字体显示为微软雅黑，Navbar高度60px，Content高度22px，上下Padding为19px，完美居中，但是在Linux下的Chrome，既没有雅黑也没有苹方，字体显示为sans-serif浏览器自定义，中文Nav项Content高度23px，整体拉伸至61px溢出，英文Nav项坍塌成20px，整体缩回58px，产生明显断裂感，是否可以考虑使用line-height做Nav的居中来规避不同字体族产生的行高差异。这里是我在Manjaro KDE上看到的撕裂和局部象素的比较
![象素对比图](https://user-images.githubusercontent.com/25009858/108091255-7e48ef80-70b6-11eb-9f59-861d66a4287a.png)
![象素整体观感](https://user-images.githubusercontent.com/25009858/108091266-80ab4980-70b6-11eb-8a97-f1a089d6bb1d.png)

**Comment by esofar** [comment]
该 bug 已修复，将会在新的版本更新。
目前请暂用 https://github.com/esofar/cnblogs-theme-silence/blob/master/dist/silence.min.css 最新文件 CSS 样式。
