### ISSUE TITLE
希望支持三级菜单

### ISSUE THREAD

**Issue by bald-head** [esofar/cnblogs-theme-silence#168]
希望navbars能够支持三级菜单

**Comment by WorkHard-For-MyMom** [comment]
> 希望navbars能够支持三级菜单

最新版本的支持三级菜单,证据如下图所示,  你试着更新一下版本
![image](https://user-images.githubusercontent.com/44394716/152477567-285240b5-6a08-423b-9e69-8322ee3f16f3.png)

**Comment by Hang-shao** [comment]
已支持了
