### ISSUE TITLE
如果标题是代码格式，会导致字体效果和其他的标题不一致

### ISSUE THREAD

**Issue by lamondlu** [esofar/cnblogs-theme-silence#17]
![image](https://user-images.githubusercontent.com/11512490/58087172-985c5200-7bf2-11e9-96e1-a4943b937ac0.png)

Hi  帅哥，一个小问题，问题如图，标题中如果带``代码高亮，右侧导航栏的显示可能和其他的不一样。

问题页面：
https://www.cnblogs.com/lwqlun/p/10894497.html

**Comment by esofar** [comment]
多谢反馈，我尽快修复下。

**Comment by esofar** [comment]
Fixed.
