### ISSUE TITLE
二维码鼠标放置后一直闪

### ISSUE THREAD

**Issue by Aaron-23** [esofar/cnblogs-theme-silence#172]
博客首页：https://www.cnblogs.com/wiseo/p/rainbond.html

![image](https://user-images.githubusercontent.com/50609288/144782330-0fb70fa9-79e9-47a4-bb62-d9556d7c0f83.png)

**Comment by gerryge** [comment]
一开始我这么设置也是闪，后来我把paypal的值改成了null就可以了。
sponsor: {
                enable: true,
                text: '',
                wechat: 'https://***.png',
                alipay: 'https://***.png',
                paypal: ''
            },   

修改后：
sponsor: {
                enable: true,
                text: '',
                wechat: 'https://***.png',
                alipay: 'https://***.png',
                paypal: null
            },

**Comment by esofar** [comment]
未设置`text`会触发该问题，最新版本修复。
