### ISSUE TITLE
赞赏功能，如何去除 paypal

### ISSUE THREAD

**Issue by wswind** [esofar/cnblogs-theme-silence#179]
不设置paypal，但是paypal图标仍旧展示，请问支持去除paypal吗？
![image](https://user-images.githubusercontent.com/18399096/154205930-11d8a70d-a93d-47ab-ad6b-0e8a1a8ec221.png)

**Comment by esofar** [comment]
最新版本已修复，不设置不显示。

**Comment by wswind** [comment]
感谢
