### ISSUE TITLE
希望显示总阅读量

### ISSUE THREAD

**Issue by Hang-shao** [esofar/cnblogs-theme-silence#187]
希望在侧边栏显示总阅读量

**Comment by 1870604579** [comment]
个人写的，需要使用这个主题，主题不要改
添加 js
<script src="https://files.cnblogs.com/files/XiaoYang-sir/stats.js"></script>

--------------------分割线----------------------------------------

添加 css
@import url(https://files.cnblogs.com/files/XiaoYang-sir/stats.css?t=1653797017);
#blogStats > span:nth-child(1) > span:nth-child(2){
    color: #97979f;
}

#blogStats > span:nth-child(2) > span:nth-child(2){
    color: #97979f;
}

#blogStats > span:nth-child(3) > span:nth-child(2){
    color: #97979f;
}

**Comment by 1870604579** [comment]
> 希望在侧边栏显示总阅读量

看这

**Comment by Hang-shao** [comment]
> > 希望在侧边栏显示总阅读量
> 
> 看这

**Comment by Hang-shao** [comment]
![image](https://user-images.githubusercontent.com/50350694/172306703-56e8963c-ae3b-4361-98ca-6473087517ff.png)
谢谢哈，但是按照你说的，把js和css加入后，没有变化哈。
![image](https://user-images.githubusercontent.com/50350694/172306852-ad3fb9c5-8265-4295-9d19-9d8234fe720e.png)

**Comment by Hang-shao** [comment]
感谢

**Comment by 1870604579** [comment]
> 感谢

20万的大佬
