### ISSUE TITLE
自定义菜单失效

### ISSUE THREAD

**Issue by bald-head** [esofar/cnblogs-theme-silence#189]
<img width="118" alt="image" src="https://user-images.githubusercontent.com/62256948/171204803-6157c6cc-ab29-4b8b-8aa8-e2ead5b55303.png">
更新rc2版本的后，自定义的菜单失效了，请求路径变为了undefined
<img width="239" alt="image" src="https://user-images.githubusercontent.com/62256948/171205060-93a18107-59bb-4d43-8ce3-34f44ddbadd2.png">

**Comment by wanghai0666** [comment]
将博客侧边栏公告中的chilren 修改为 children，一切正常。

**Comment by bald-head** [comment]
已解决
