### ISSUE TITLE
引用的cnblogs的js文件都403了

### ISSUE THREAD

**Issue by x1ntt** [esofar/cnblogs-theme-silence#195]
按照`README.md`文件里面说的，启动了项目，不过很多`js文件`都是`403`的状态，作者准备修一下吗？

或者说有什么解决方案？需要在项目中存一份吗？

**Comment by KoiC-UP** [comment]
在三个示例页面头部加入这行代码可以暂时解决这个问题。
`<meta name="referrer" content="no-referrer" />`
