### ISSUE TITLE
搜索功能希望保留

### ISSUE THREAD

**Issue by 52fhy** [esofar/cnblogs-theme-silence#20]
搜索功能希望保留

**Comment by 52fhy** [comment]
我自己在顶部追加了搜索：https://52fhy.cnblogs.com/

**Comment by mark-zh** [comment]
文章档案怎么添加呢？

**Comment by RealIvyWong** [comment]
我解决了这个问题。
通过删除 css 文件中的 #sidebar_search 这一项。这样就可以在侧边栏看到下图了（前提是设置里设置了显示搜索栏）。
![image](https://user-images.githubusercontent.com/42825492/68466859-2e8f3d80-0250-11ea-9aa7-b74b0ab19e82.png)

**Comment by RealIvyWong** [comment]
顺便，日历也可以同样通过删除 #blogCalendar 这一项来显示在侧边栏。
欢迎围观效果。
https://www.cnblogs.com/IvyWong/

**Comment by esofar** [comment]
抓到一只程序媛小姐姐，欢迎围观。@RealIvyWong 

搜索功能正在添加，日历没实用，暂不考虑加咯。
