### ISSUE TITLE
按照部署文档部署后，排版是乱的

### ISSUE THREAD

**Issue by Seifon** [esofar/cnblogs-theme-silence#24]
版本：2.0.1

照着部署文档一步一步操作的，可排版是乱的。

另外，为什么你的博客使用的版本是2.1.0，而github上的版本确是2.0.1的代码呢？

**Comment by esofar** [comment]
我自己博客之前用作调试，忘记更换版本，不影响你说的问题。
估计你还是部署有点问题，可否提供下博客地址，我看下。

**Comment by seifonx** [comment]
部署的问题解决了， 我当时忘了取消勾线CSS默认样式。

**Comment by seifonx** [comment]
主题很棒，要是有hexo的就更好了

**Comment by esofar** [comment]
解决就好。
抱歉，这是博客园主题，不会支持 hexo 的。再者，hexo 漂亮的主题很多的呀。
