### ISSUE TITLE
Tag列表显示异常

### ISSUE THREAD

**Issue by TieWay59** [esofar/cnblogs-theme-silence#25]
![图片](https://user-images.githubusercontent.com/40034603/61997639-fddb2c00-b0d6-11e9-8b4f-28e31f5ad7f3.png)
虽然没啥功能性影响，但是视觉上感觉有点异常。

**Comment by esofar** [comment]
能明确说明下异常在何处吗？我只能猜一下：
1. `GameDesign::Engine::Cocos` 这个标签不是你创建的？这个不太可能。
2. `GameDesign::Engine::Cocos` 标签过长，导致表格当前列过宽？ 当前这个列宽是自适应的，如果你有更好的写法，欢迎贡献代码。

**Comment by TieWay59** [comment]
谢谢了，其实我的意思是标签如果名字太长，会导致上下的都一起匹配这个宽度了，我也没有很理想的解决办法，可能是有一点强迫症思维了，我关了吧。
