### ISSUE TITLE
文章页不显示目录，点击目录按钮也没有反应

### ISSUE THREAD

**Issue by imzry** [esofar/cnblogs-theme-silence#27]
博主您好，我按照您的教程部署完主题后，发现文章的目录不显示，点击显示目录的按钮也没有反应。我在网页检查元素中找到一个js加载的错误，不知道是不是因为这个的原因导致的。请问博主该怎么解决呀？

![080fa9f3aead27814f726330b31e521](https://user-images.githubusercontent.com/23444836/62017414-1fc4d380-b1e9-11e9-96fc-257594081875.png)

**Comment by esofar** [comment]
1.从输出内容上看，这是 Google 的分析脚本，与本主题无关。
2.目录不显示问题，请确认你的博文是使用哪级标题`h2, h3, h4 ...`等，再查看你的 `catalog` 相关配置是否合适。
3.如果还搞不定，方便的话可以提供博客地址一块分析解决。

**Comment by imzry** [comment]
解决了，我没有注意到默认不支持h1标题
谢谢
