### ISSUE TITLE
新版参数配置问题

### ISSUE THREAD

**Issue by hippieZhou** [esofar/cnblogs-theme-silence#28]
你好，我在更新你最新发布的 2.0.1 版本后进行相关配置后存在以下问题：

- github 配置参数中如果使用了 `color` 参数进行修改会导致博客首页左侧信息和网站底部信息无法显示；
- 对应个人博客中如果使用了图片的话，点击打开图片会全屏显示，但是不会像你博客那样在右下角显示一个关闭按钮；

还请大佬检查一下我上述描述的两个问题，如果是我姿势不正确的问题还请指出，谢谢。

**Comment by esofar** [comment]
我测试过才提交发布的，配置应该没问题。
尝试先把你自定义添加的脚本样式移除，再看看效果。

**Comment by hippieZhou** [comment]
嗯，不好意思，是我添加有自定义脚本导致的，目前已解决。给大佬点赞！
