### ISSUE TITLE
博客显示异常

### ISSUE THREAD

**Issue by 986244073** [esofar/cnblogs-theme-silence#29]
[https://www.cnblogs.com/yancy9862/](url)

头像跑到下面去了

**Comment by esofar** [comment]
应该是没有选中默认 Custom 模板造成的的页面混乱，请仔细阅读部署文档。

**Comment by 986244073** [comment]
勾选了的

**Comment by esofar** [comment]
@986244073 请上传配置截图

**Comment by 986244073** [comment]
![fehelper-i-cnblogs-com-Configure-aspx-1565013989269](https://user-images.githubusercontent.com/16508677/62470608-6314d880-b7cd-11e9-98de-0143be91b124.png)
![fehelper-i-cnblogs-com-Preferences-aspx-1565014036433 (1)](https://user-images.githubusercontent.com/16508677/62470695-92c3e080-b7cd-11e9-9abf-29cd6f918bee.png)

**Comment by esofar** [comment]
【禁用模板默认CSS】取消勾选。请查看部署文档校对。
