### ISSUE TITLE
TinyMCE编辑器展开的代码复制时异常跳转

### ISSUE THREAD

**Issue by yinhaiping105** [esofar/cnblogs-theme-silence#31]

**Comment by esofar** [comment]
给个链接 或 截图。

**Comment by yinhaiping105** [comment]
![image](https://user-images.githubusercontent.com/50862201/62677497-199cd700-b9e1-11e9-9aa5-d4fe339c49c2.png)

TinyMCE编辑器插入的代码没有高亮显示.
能做成这样已经不错了,Markdown支持的很好,TinyMCE要是优化一下就更好了,毕竟这个编辑器用的也是很多的.

**Comment by yinhaiping105** [comment]
我做的gif动态图,这里显示不出来,给你链接去试下吧
[TinyMCE编辑](https://www.cnblogs.com/yinhaiping/p/11309550.html)

**Comment by esofar** [comment]
TinyMCE 编辑器的代码是使用内联样式修饰的，不好定制。若使用原有代码高亮样式，又感觉与主题不太搭配，所以统一了一个颜色。如果你有更好的办法欢迎交流。

代码复制时异常跳转，这个问题已经修复。

**Comment by yinhaiping105** [comment]
👍

**Comment by esofar** [comment]
建议更换使用 markdown 编辑器吧
