### ISSUE TITLE
添加paypal二维码点击会弹出二维码图片

### ISSUE THREAD

**Issue by loanon** [esofar/cnblogs-theme-silence#32]
示例代码中只填写了Alipay和WeChatpay的收款码，当也填写了PayPal的收款码的时候，点击PayPal的收款码，会新建标签页打开收款码图片，不是和支付宝和微信收款一样弹窗显示二维码图片。看了代码是代码就这么写的。是不是作者开发的 时候测试没改回来

**Comment by esofar** [comment]
目前`paypal`应该填写一个链接，跳转到付款地址。因为我没使用过 PayPal，不清楚其支持二维码付款。我后面研究下再优化吧。

**Comment by loanon** [comment]
这个指的是paypal.me的链接吧？这样也对。我是看也可以生成收款码就做了个收款码。看来也没问题。

**Comment by loanon** [comment]
谢谢指教！
