### ISSUE TITLE
感谢作者。你的作品默认皮肤是哪一个，改完以后乱了

### ISSUE THREAD

**Issue by Mazongdiulejinguzhou** [esofar/cnblogs-theme-silence#41]

**Comment by esofar** [comment]
请给个截图或详细说明你遇到的问题。

**Comment by Mazongdiulejinguzhou** [comment]
![1](https://user-images.githubusercontent.com/47622278/67372360-5a53c780-f5b0-11e9-9d2c-217bba81f81b.png)
![2](https://user-images.githubusercontent.com/47622278/67372365-5c1d8b00-f5b0-11e9-8672-a519599d6c4d.png)

**Comment by esofar** [comment]
配置不对，请参考部署文档 [其他配置](https://github.com/esofar/cnblogs-theme-silence/blob/master/docs/deploy.md#%E5%85%B6%E4%BB%96%E9%85%8D%E7%BD%AE) 小节。

```
在「博客皮肤」处选择博客园官方标准模板 Custom；
把「禁用模板默认CSS」复选框取消勾选。
```

**Comment by Mazongdiulejinguzhou** [comment]
自己粗心，感谢作者

**Comment by esofar** [comment]
看上面截图，你的 JS 引用貌似用我的，万一我有所改动或删掉，你就尴尬了，最好自己上传。
```
<script src="https://blog-static.cnblogs.com/files/esofar/silence.min.js"></script>
```

**Comment by Mazongdiulejinguzhou** [comment]
好的  刚才  测试用的  马上改
