### ISSUE TITLE
[图片][阴影效果] 如何给图片添加阴影效果

### ISSUE THREAD

**Issue by JasonGrass** [esofar/cnblogs-theme-silence#43]
示例如这篇博客：
[[WPF自定义控件库]使用WindowChrome的问题 - dino.c - 博客园](https://www.cnblogs.com/dino623/p/problems_of_WindowChrome.html#idx_7 ) 

![image](https://user-images.githubusercontent.com/10756994/68171289-1c8e7000-ffae-11e9-9e00-109124f1999c.png)

不知道是不是博主自己修改出来的效果，不过很赞啊。可以考虑作为默认配置。

阴影效果可以增加文字与图片的区别，提升布局效果。

**Comment by esofar** [comment]
很好的建议，已更新。
