### ISSUE TITLE
是否有可能在标签页实现标签云的效果

### ISSUE THREAD

**Issue by RealIvyWong** [esofar/cnblogs-theme-silence#46]
根据不同标签有的文章数，显示标签文字的大小，大概呈现出一个标签云的样式。
不确定博客园是否支持定制标签页。
类似如下
![image](https://user-images.githubusercontent.com/42825492/68467432-21268300-0251-11ea-8253-fea9c5316e13.png)

**Comment by esofar** [comment]
很难，很难。博客园的标签页使用`table`标签做的。
