### ISSUE TITLE
release 都删了？

### ISSUE THREAD

**Issue by WeihanLi** [esofar/cnblogs-theme-silence#47]
这两天博客有点乱掉了，js 是直接引用的博主的 js，这两天突然出来了搜索框，导航菜单也多出来了几个菜单，大佬有空的时候帮我看一下吧

![image](https://user-images.githubusercontent.com/7604648/69293335-89a73400-0c43-11ea-9122-b5d564ea640f.png)

搜索框自己加了一行 css 隐藏了 `.esa-search-box,.esa-sub-navs{display:none;}`

博客地址：<https://www.cnblogs.com/weihanli/>

**Comment by esofar** [comment]
兄弟，不要用我的 JS 文件，你自己上传下。我这边折腾你那边肯定会跟着变啊。

**Comment by WeihanLi** [comment]
嗯，所以想来 release 里面找一下 js 上传一下 😢

**Comment by esofar** [comment]
因为之前发的 release 有很多未修复的问题，索性全删了。您直接克隆源码到 `dist`目录拿去最新版就行。

**Comment by WeihanLi** [comment]
好的，我去试试，谢谢大佬

**Comment by esofar** [comment]
CSS 也有同步更新。

**Comment by WeihanLi** [comment]
更新了，可以了，感谢大佬
