### ISSUE TITLE
博客园小白，想请问一下，底栏没有分页是什么情况

### ISSUE THREAD

**Issue by haibingqingxie** [esofar/cnblogs-theme-silence#48]
[如题，严格按照教程部署设置，[这是我博客园地址 ](https://www.cnblogs.com/haibinqingxie/)。上传了一些文章后，发现底栏没有下一页之类的分页器。

这个分页代码是需要自己添加的吗？如果可以的话，能不能做一个推荐。如果不是自己添加的，是否是主题的bug？

另外，搜索功能仍然有问题，搜索的图标展示错位。

**Comment by haibingqingxie** [comment]
我是下载了最新版本的，才出现图标错位的，之前版本2.0.2正常

**Comment by esofar** [comment]
你后台 JS 加载了两次。

**Comment by haibingqingxie** [comment]
检查了一下，初始化了两次。

**Comment by haibingqingxie** [comment]
不好意思，误报 bug了

**Comment by haibingqingxie** [comment]
关于分页代码，请问有什么推荐的吗

**Comment by esofar** [comment]
分页代码？推荐？分页是博客园官方功能，每页数量可以在后台设置。

**Comment by haibingqingxie** [comment]
谢谢啦，我在验证了手机号之后，分页就出来了
