### ISSUE TITLE
如何配置左上角的GitHub小图标点击时在新标签打开

### ISSUE THREAD

**Issue by JasonCeng** [esofar/cnblogs-theme-silence#51]
如题，如何配置左上角的GitHub小图标点击时在新标签打开？

**Comment by Liuyel** [comment]
src/silence.js文件下，找到构建 Github Corner 的方法   buildGithubCorner()，修改<a href="${config.link}" class="github-corner" title="Fork me on GitHub">为
<a href="${config.link}" class="github-corner" title="Fork me on GitHub" target="_blank">
应该就可以了

**Comment by esofar** [comment]
@Liuyel 期待你贡献个`github.target`配置参数哦。
