### ISSUE TITLE
想要隐藏页脚HTML代码中的站长统计

### ISSUE THREAD

**Issue by DinoChan** [esofar/cnblogs-theme-silence#55]
我在页脚HTML代码中加入了站长统计的内容，设置如下：

![bbbb](https://user-images.githubusercontent.com/6076257/70499965-4b6fa700-1b55-11ea-9feb-7bc2a7317bcc.png)

然后在博客里显示在博客的中间了，可以在下面的博客里看到。

[使用CompositionGeometricClip裁剪复杂图形及进行动画](https://www.cnblogs.com/dino623/p/using_compositiongeometricclip_to_cut_and_animate_complex_graphics.html)

![aaaa](https://user-images.githubusercontent.com/6076257/70500014-6cd09300-1b55-11ea-80ef-cdbe4e96d41f.png)

请问可以隐藏这些内容吗？

**Comment by esofar** [comment]
加个隐藏样式就行。
```
a[title=站长统计] {
    display: none;
}
```

**Comment by DinoChan** [comment]
> 
> 
> 加个隐藏样式就行。
> 
> ```
> a[title=站长统计] {
>     display: none;
> }
> ```

这个方法可行，谢谢
