### ISSUE TITLE
移动端下导航栏

### ISSUE THREAD

**Issue by youthred** [esofar/cnblogs-theme-silence#57]
移动端下的导航栏左边距都挤到一起了，折叠下拉的内容也不对吧

**Comment by MakerGYT** [comment]
试试[cnblogs-theme-next](https://github.com/MakerGYT/cnblogs-theme-next)
![](https://static01.imgkr.com/temp/4e9579bc084e4740873687ef112722f5.gif)
[预览](https://www.cnblogs.com/makergyt)
