### ISSUE TITLE
markdown下，侧边阅读目录的标题分级有问题

### ISSUE THREAD

**Issue by Z-Echo** [esofar/cnblogs-theme-silence#59]
嗨~
非常喜欢你的这款主题，但是我发现一个markdown的问题，侧边的阅读目录的标题分级是从markdown的二级标题开始的，一级标题没办法显示，相关问题详情描述已发至你的邮箱。

**Comment by WeihanLi** [comment]
我一般正文都是用的二级标题，不会用一级标题，只有在文章开头会用一个一级标题

**Comment by Z-Echo** [comment]
感谢回复，我试着调整了你的html代码已经可以显示二级标题了，谢谢！
