### ISSUE TITLE
体验小建议

### ISSUE THREAD

**Issue by buerbl** [esofar/cnblogs-theme-silence#61]
![](http://javahouse.xyz/20200111131601.png)  旁边的滚动栏太细了，找不到他，能否加粗一下

**Comment by w4ctech** [comment]
![image](https://user-images.githubusercontent.com/33955669/72320426-9cd2ff00-36dc-11ea-91d4-9a846fd6748c.png)
::-webkit-scrollbar {
    width: 14px !important; 
    height: 3px
}

加到你的自定义css 上

**Comment by buerbl** [comment]
![](http://javahouse.xyz/20200114151027.png)  可以
