### ISSUE TITLE
“阅读全文 禄”

### ISSUE THREAD

**Issue by Reliacrt** [esofar/cnblogs-theme-silence#69]
如标题“阅读全文 禄”，这个禄字是怎么回事呢，首页中跳转到具体博客的按钮显示的是这个，而不是类似于>>的符号。

**Comment by Reliacrt** [comment]
我自己解决了😂，替换了一下css里面这个东西对应的属性值，换了个能显示的值。

**Comment by esofar** [comment]
已修复，建议安装最新版。
