### ISSUE TITLE
手机端文章内容图片无法显示完整

### ISSUE THREAD

**Issue by HHChaos** [esofar/cnblogs-theme-silence#7]
使用本主题时，在手机端（将桌面浏览器宽度改变到较小尺寸同样可以复现）打开博客页，如果文章内容中包含图片，且图片尺寸比较大，网页不会对图片进行适应网页宽度的缩放，导致图片只能显示左边的一部分，请问这个问题是否有计划更改呢？

**Comment by esofar** [comment]
已修复，点击查看 [提交记录]( https://github.com/esofar/cnblogs-theme-silence/commit/8184a9776bc8d26075a0b5eca4214186b29c5488)。

**Comment by HHChaos** [comment]
> 已修复，点击查看 [提交记录](https://github.com/esofar/cnblogs-theme-silence/commit/8184a9776bc8d26075a0b5eca4214186b29c5488)。

赞！这么快！
