### ISSUE TITLE
设置 avatar favicon navigation 无效，我漏掉了什么设置？求指导。

### ISSUE THREAD

**Issue by JasonGrass** [esofar/cnblogs-theme-silence#70]
按照部署文档，
[cnblogs-theme-silence/deploy.md at master · esofar/cnblogs-theme-silence · GitHub](https://github.com/esofar/cnblogs-theme-silence/blob/master/docs/deploy.md ) 
设置 导航，头像等无效，但是修改 GitHub 导航等是有效的。

我是不是漏掉了什么操作？（博客园的控件显示设置已打开）

---
完整设置：

```
<script src="https://blog-static.cnblogs.com/files/jasongrass/silence.min.js"></script>
<script type="text/javascript">
    $.silence({
        avatar: 'https://images.cnblogs.com/cnblogs_com/jasongrass/1664002/o_200308023501C979A116-F45A-4495-9E05-18A84E14E070.JPG',
        favicon: 'https://blog-static.cnblogs.com/files/jasongrass/favicon.ico',
        navigation: [
        {
                title: '归档',
                url: 'https://www.cnblogs.com/jasongrass/p/'
        },
            {
                title: '导航',
                chilren: [
                    {
                        title: '谷歌',
                        url: 'https://www.google.com/',
                    },
                    {
                        title: '百度',
                        url: 'https://www.baidu.com/',
                    },
                ]
            },
        ],
        catalog: {
            enable: true,
            move: true,
            index: true,
            level1: 'h2',
            level2: 'h3',
            level3: 'h4',
        },
        signature: {
            enable: true,
            author: 'JasonGrass',
            home: 'https://jgrass.cc',
            license: '署名 4.0 国际',
            link: 'https://creativecommons.org/licenses/by/4.0'
        },      
        github: {
            enable: true,
            color: '#fff',
            fill: '#151513',
            link: 'https://github.com/JasonGrass',
        }
    });
</script>

```

**Comment by lemonL** [comment]
我也遇到了这个问题，好像更新了这个版本就会有这个问题，我用之前的版本的是可以的。

**Comment by JasonGrass** [comment]
现在可以了（没有做什么修改），看起来是博客园自身的问题。

**Comment by AncientFairy** [comment]
OK 谢谢 我试试






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JasonLiu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月15日(星期天) 晚上6:06
收件人:&nbsp;"esofar/cnblogs-theme-silence"<cnblogs-theme-silence@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [esofar/cnblogs-theme-silence] 设置 avatar favicon navigation 无效，我漏掉了什么设置？求指导。 (#70)





 
现在可以了（没有做什么修改），看起来是博客园自身的问题。

**Comment by Raysuner** [comment]
请问这两个路径是怎么获取的？
avatar: 'https://images.cnblogs.com/cnblogs_com/jasongrass/1664002/o_200308023501C979A116-F45A-4495-9E05-18A84E14E070.JPG',
        favicon: 'https://blog-static.cnblogs.com/files/jasongrass/favicon.ico',



> 按照部署文档，
> [cnblogs-theme-silence/deploy.md at master · esofar/cnblogs-theme-silence · GitHub](https://github.com/esofar/cnblogs-theme-silence/blob/master/docs/deploy.md)
> 设置 导航，头像等无效，但是修改 GitHub 导航等是有效的。
> 
> 我是不是漏掉了什么操作？（博客园的控件显示设置已打开）
> 
> 完整设置：
> 
> ```
> <script src="https://blog-static.cnblogs.com/files/jasongrass/silence.min.js"></script>
> <script type="text/javascript">
>     $.silence({
>         avatar: 'https://images.cnblogs.com/cnblogs_com/jasongrass/1664002/o_200308023501C979A116-F45A-4495-9E05-18A84E14E070.JPG',
>         favicon: 'https://blog-static.cnblogs.com/files/jasongrass/favicon.ico',
>         navigation: [
>         {
>                 title: '归档',
>                 url: 'https://www.cnblogs.com/jasongrass/p/'
>         },
>             {
>                 title: '导航',
>                 chilren: [
>                     {
>                         title: '谷歌',
>                         url: 'https://www.google.com/',
>                     },
>                     {
>                         title: '百度',
>                         url: 'https://www.baidu.com/',
>                     },
>                 ]
>             },
>         ],
>         catalog: {
>             enable: true,
>             move: true,
>             index: true,
>             level1: 'h2',
>             level2: 'h3',
>             level3: 'h4',
>         },
>         signature: {
>             enable: true,
>             author: 'JasonGrass',
>             home: 'https://jgrass.cc',
>             license: '署名 4.0 国际',
>             link: 'https://creativecommons.org/licenses/by/4.0'
>         },      
>         github: {
>             enable: true,
>             color: '#fff',
>             fill: '#151513',
>             link: 'https://github.com/JasonGrass',
>         }
>     });
> </script>
> ```

**Comment by JasonGrass** [comment]
https://github.com/esofar/cnblogs-theme-silence/issues/70#issuecomment-609048527
@Raysuner  
博客园可以上传图片，并获取链接：
![image](https://user-images.githubusercontent.com/10756994/78464770-e9e4d100-771f-11ea-97af-eb80a4519b2d.png)

**Comment by Raysuner** [comment]
@JasonGrass 哈哈，谢谢，搞定了

**Comment by JasonGrass** [comment]
最近都没有发现这个问题，此 issue 可以关闭了。
