### ISSUE TITLE
提交评论和删除评论时页面不响应，要刷新才正常

### ISSUE THREAD

**Issue by ChaselLHL** [esofar/cnblogs-theme-silence#72]
1. 提交完评论，评论列表没有刷新, 没有修改和删除按钮
![comment](https://user-images.githubusercontent.com/34236185/76389563-752fa880-63a6-11ea-8544-294f44510a8d.png)
2  删除评论， 评论列表没有刷新， 页面有残留元素

**Comment by ChaselLHL** [comment]
div.commentform textarea{
height: auto !important;
}
.bq_post_comment p{
display: block !important
}
加上这两个样式可以暂时解决

**Comment by esofar** [comment]
Fixed.
