### ISSUE TITLE
Markdown 目录索引的锚点有点问题

### ISSUE THREAD

**Issue by ka1n4t** [esofar/cnblogs-theme-silence#77]
老哥你好，好像有个bug

Markdown的 [toc]语法是根据后面的Markdown节点自动生成一个目录，比如

```
[TOC]
#header1
```

会在header1的前面生成一个header1超链接，指向#header1，点击之后自动跳到header1锚点。而header1标题的位置就是一个超链接，比如\<a href="#header1">xxx\</a>

但是你这里的实现好像是把目录的锚点用一串数值代替了，header1处的超链接变成了\<a href="#1234567890">xxx\</a>。因此，如果点击[toc]自动生成的目录的话，无法跳到对应的锚点。

**Comment by MakerGYT** [comment]
试试[next-theme](https://www.cnblogs.com/makergyt/p/13220468.html),无需写入TOC,自动生成目录

**Comment by esofar** [comment]
该问题已在最新版本中修复。
