### ISSUE TITLE
字体虚化问题

### ISSUE THREAD

**Issue by wunsiang** [esofar/cnblogs-theme-silence#82]
首先感谢作者提供这么好的主题，真的非常感谢，但是我发现主题有一个问题就是字会虚化，我尝试更换了字体但还是存在虚化的问题，所以能否请作者有时间的时候关注下呢，感谢！

**Comment by esofar** [comment]
抱歉，久等了。之前的博文字号偏小、字体偏细，看起来会有些虚化，新版重视该问题。建议升级版本解决该问题。
