### ISSUE TITLE
新版edge浏览器菱形样式兼容性问题

### ISSUE THREAD

**Issue by wswind** [esofar/cnblogs-theme-silence#83]
![image](https://user-images.githubusercontent.com/18399096/81528908-46c34f00-9390-11ea-800a-4c8f938afd26.png)
![image](https://user-images.githubusercontent.com/18399096/81528951-5b9fe280-9390-11ea-99a4-7644b8f424f4.png)

**Comment by esofar** [comment]
通过升级可以修复该问题。
