### ISSUE TITLE
按照部署文档部署之后，左侧边栏不显示

### ISSUE THREAD

**Issue by haozhihan** [esofar/cnblogs-theme-silence#93]
![image](https://user-images.githubusercontent.com/60099470/88456114-ac15df00-cead-11ea-8109-0cbc5129ee41.png)
![image](https://user-images.githubusercontent.com/60099470/88456127-c2bc3600-cead-11ea-96ae-97d2db12dbf7.png)

**Comment by William9527wn** [comment]
我也是这个问题
